### ISSUE TITLE
[Suggestion] Auto input attacks

### ISSUE THREAD

**Issue by rpalmon** [togenyan/Yo-kai_Editor_Getto#1]
Hello,
As a person who doesn't understand Japanese, when adding a Yo-Kai, there is an option to chose the attacks. That is the hard part. When I just put a random attack for all the options in the Yo-Kai and save it, the Yo-Kai would not show up. I think that it is saying that the attacks are not "compatable." 

What I am asking is if you could add a button to [Auto Input Attacks]. That would be great. 
If you add it, could you let me know what the button is named in Japanese?

Also could you order the Yo-Kai in numbers from 1-??? And add a search function like all the other Yo-Kai Editors? Thanks

**Comment by togenyan** [comment]
> What I am asking is if you could add a button to [Auto Input Attacks]. That would be great.

Added. The button label is "デフォルト". It's located below the combo box for 3rd attack.
